#!/bin/sh

### BEGIN INIT INFO
# Provides: token_app
# Should-Start: postgresql
# Should-Stop: postgresql
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: starts the token_app app server
### END INIT INFO

set -e

umask 022

APP_ROOT=/home/mwarnock/token_app
PID=$APP_ROOT/tmp/pids/glassfish.pid
ENV=production
OPTS="-S glassfish --contextroot / --port 3000 --environment production --runtimes 1 --runtimes-min 1 --runtimes-max 2 -P $PID --daemon $APP_ROOT"
USER=mwarnock

. /lib/lsb/init-functions

case $1 in
start)
	log_daemon_msg "Starting Token App app server" "token_app"
	if start-stop-daemon -c $USER --start --quiet --oknodo --pidfile $PID --exec /usr/bin/jruby -- $OPTS; then
	   log_end_msg 0
	else
	   log_end_msg 1
	fi
        ;;
stop)
	log_daemon_msg "Stopping Token App app server" "token_app"
	if start-stop-daemon --stop --quiet --oknodo --pidfile $PID; then
	   log_end_msg 0
	else
	   log_end_msg 1
	fi
        ;;

restart|reload)
	log_daemon_msg "Restarting Token App app server" "token_app"
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PID
	if start-stop-daemon -c $USER --start --quiet --oknodo --pidfile $PID --exec /usr/bin/jruby -- $OPTS; then
	   log_end_msg 0
	else
	   log_end_msg 1
	fi
        ;;
*)
        log_action_msg "Usage: /etc/init.d/ssh {start|stop|reload|force-reload|restart|try-restart|status}"
        exit 1

esac
