#!/bin/sh

### BEGIN INIT INFO
# Provides: token_app
# Should-Start: postgresql
# Should-Stop: postgresql
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: starts the token_app app server
### END INIT INFO

set -e

umask 022

APP_ROOT=/home/mwarnock/token-app
PID=$APP_ROOT/tmp/pids/glassfish.pid
#ENV=production
ENV=development
OPTS="-S glassfish --contextroot / --port 3000 --environment $ENV --runtimes 1 --runtimes-min 1 --runtimes-max 2 -P $PID --daemon $APP_ROOT"
USER=mwarnock
JRUBY="/opt/jruby/jruby-1.5.1/bin/jruby"
GEM_HOME="/opt/jruby/jruby-1.5.1/lib/ruby/gems/1.8"
JAVA_HOME="/opt/java/jdk1.6.0_21"

. /lib/lsb/init-functions

case $1 in
start)
	log_daemon_msg "Starting Token App app server" "token_app"
	if env JAVA_HOME="$JAVA_HOME" GEM_HOME="$GEM_HOME" start-stop-daemon -c $USER --start --quiet --oknodo --pidfile $PID --exec $JRUBY -- $OPTS; then log_end_msg 0
	else
	   log_end_msg 1
	fi
        ;;
stop)
	log_daemon_msg "Stopping Token App app server" "token_app"
	if start-stop-daemon --stop --quiet --oknodo --pidfile $PID; then
	   log_end_msg 0
	else
	   log_end_msg 1
	fi
        ;;

restart|reload)
	log_daemon_msg "Restarting Token App app server" "token_app"
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PID
	if env JAVA_HOME="$JAVA_HOME" GEM_HOME="$GEM_HOME" start-stop-daemon -c $USER --start --quiet --oknodo  --pidfile $PID --exec $JRUBY -- $OPTS; then
	   log_end_msg 0
	else
	   log_end_msg 1
	fi
        ;;
*)
        log_action_msg "Usage: $0 {start|stop|reload|force-reload|restart|try-restart|status}"
        exit 1

esac
