# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19b3b7ba60dcbda67a0b01345a41385508e3061d9aa357e141184ffb01be91c4dab7f9560739f26812a6a9d974a48c0a0d7033a379785c1fce2db1f98f55417d

test:
  secret_key_base: 1348ace47bd79815a396282da3cd9b606294fa883242deb5a551c35a805adb5c60c8bad3453bdd5c2a0cceafa6a393ed398007f2e014234e1a25ef74f5edfca7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
